'use client'
import { useState } from 'react'
import { AnimatePresence, motion, useScroll, useTransform } from 'framer-motion'
import { ChevronDown, Mail, Instagram, Linkedin, Youtube, Trophy, Medal, Cpu, X } from 'lucide-react'
import { fest, events, faqs } from '@/lib/data'
import { Navbar } from '@/components/Navbar'
import { PixelButton } from '@/components/PixelButton'
import { Countdown } from '@/components/Countdown'
import { EventLevel } from '@/components/EventLevel'
import { PixelCloud, PixelRobot, Sparkles, Vault } from '@/components/PixelArt'
import { SchedulePanel } from '@/components/SchedulePanel'
import { SkyWorld } from '@/components/SkyWorld'
import FooterPixelSparks from '@/components/ui/footer-pixel-sparks'
import EventCoverflow from '@/components/EventCoverflow'

const Reveal=({children}:{children:React.ReactNode})=><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.45}}>{children}</motion.div>
export default function Page(){const [modal,setModal]=useState<readonly string[]|null>(null);const [faq,setFaq]=useState<number|null>(null);const {scrollY}=useScroll();const moonY=useTransform(scrollY,[0,900],[0,125]);const titleY=useTransform(scrollY,[0,900],[0,58]);const mascotY=useTransform(scrollY,[0,900],[0,38]);const copyY=useTransform(scrollY,[0,900],[0,22]);return <main className="game-world"><SkyWorld/><Navbar/><section id="home" className="hero zone"><motion.div style={{y:moonY}} className="pixel-moon"><i/><b/><span/></motion.div><PixelCloud className="hero-cloud one"/><PixelCloud className="hero-cloud two"/><Sparkles/><div className="satellite">◉<i>⌁</i></div><div className="hero-content"><motion.div initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} className="eyebrow">LEVEL 01　·　ANNUAL COLLEGE ROBOTICS FEST</motion.div><motion.div className="mascot-float" style={{y:mascotY}}><PixelRobot className="hero-robot"/></motion.div><motion.div className="hero-title-parallax" style={{y:titleY}} initial={{scale:.9}} animate={{scale:1}} transition={{delay:.08,type:'spring',stiffness:150,damping:15}}><h1><span data-title="ROBO">ROBO</span><span data-title="FIESTA">FIESTA</span><em data-title="’26">’26</em></h1></motion.div><motion.div style={{y:copyY}} className="hero-copy-parallax"><p className="tagline">Where Circuits Come Alive.</p><p className="hero-meta">{fest.date}　•　{fest.venue}</p><div className="hero-actions"><PixelButton>Register Your Team</PixelButton><PixelButton href="#events" secondary>Explore Events</PixelButton></div></motion.div></div><a href="#mission" className="scroll-hint">SCROLL TO ENTER THE ARENA <b>↓</b></a></section>

<section id="mission" className="mission zone"><Reveal><div className="transmission"><span className="status-dot"/><div className="chip-arm">╚═◈═╗</div><p className="eyebrow dark">TRANSMISSION RECEIVED</p><h2>THE ARENA IS OPEN.</h2><p>RoboFiesta’26 brings together the sharpest student builders for three days of robotics, innovation, competition, workshops, and high-voltage ideas.</p><div className="stat-row">{[['⚙','20+ Events'],['♛','₹X Lakhs in Prizes'],['▦','3 Days of Innovation'],['⌘','1000+ Participants']].map(([icon,x])=><b key={x}><i aria-hidden="true">{icon}</i>{x}</b>)}</div><p className="count-label">TEAM REGISTRATION CLOSES IN</p><Countdown/><div className="mission-ctas"><PixelButton>Start Registration</PixelButton><a href="#events">Download Rulebook →</a></div></div></Reveal></section>

<section id="events" className="events zone"><div className="section-head"><p className="eyebrow dark">LEVEL SELECT</p><h2>CHOOSE YOUR ARENA</h2><p>Pick a challenge. Assemble your crew. Let the machines do the talking.</p></div><EventCoverflow/><div className="event-grid">{events.map(e=><EventLevel key={e[0]} event={e} onOpen={()=>setModal(e)}/>)}</div></section>

<section id="schedule" className="schedule zone"><Reveal><div className="section-head"><p className="eyebrow dark">COMMAND CENTER</p><h2>MISSION TIMELINE</h2></div><SchedulePanel/></Reveal></section>

<section id="prizes" className="prizes zone"><Reveal><div className="prize-copy"><p className="eyebrow dark">LEVEL REWARD</p><h2>UNLOCK THE<br/>PRIZE VAULT</h2><p>Bring the best build, the smartest code, and the boldest idea. The arena rewards teams that push beyond the expected.</p><PixelButton>View Prize Categories</PixelButton></div></Reveal><div className="vault-stage"><Sparkles/><Vault/></div><div className="prize-cards">{[[Trophy,'Champion','Cash Prize + Trophy'],[Medal,'Runner-Up','Cash Prize + Trophy'],[Cpu,'Special Awards','Best Design, Best Innovation, Crowd Favorite']].map(([Icon,title,copy],index)=>{const I=Icon as typeof Trophy;return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}} className="prize-card" key={String(title)}><I/><h3>{String(title)}</h3><p>{String(copy)}</p><small>DETAILS TBA</small></motion.div>})}</div></section>

<section className="experience zone"><div className="section-head"><p className="eyebrow dark">XP UNLOCKED</p><h2>MORE THAN A COMPETITION</h2></div><div className="feature-grid">{[['⌁','Build','Hands-on workshops, mentor sessions, and open build zones.'],['⚙','Battle','High-energy robotics competitions across skill levels.'],['◎','Meet','Connect with builders, alumni, experts, and campus communities.'],['↗','Launch','Showcase projects, find collaborators, and build your portfolio.']].map(([icon,t,d])=><Reveal key={t}><article className="feature"><i>{icon}</i><h3>{t}</h3><p>{d}</p></article></Reveal>)}</div></section>

<section id="sponsors" className="sponsors zone"><div className="section-head"><p className="eyebrow dark">PIT CREW</p><h2>POWERING THE BUILDERS</h2><p>RoboFiesta’26 is made possible by organizations that believe in the next generation of engineers.</p></div>{['Title Sponsor','Gold Partners','Community Partners','Media Partners'].map((tier,i)=><motion.div initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="sponsor-row" key={tier}><h3>{tier}</h3><div>{Array.from({length:i===0?1:i===1?3:4}).map((_,x)=><span key={x}>YOUR<br/>LOGO HERE</span>)}</div></motion.div>)}<div className="sponsor-cta"><PixelButton>Partner With Us</PixelButton><a href="#contact">Sponsor brochure ↗</a></div></section>

<section id="faq" className="faq zone"><div className="section-head"><p className="eyebrow dark">HELP DESK</p><h2>SYSTEM DIAGNOSTICS</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="faq-item" key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}><span>0{i+1}</span>{q}<ChevronDown className={faq===i?'flip':''}/></button><AnimatePresence>{faq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{a}</motion.p>}</AnimatePresence></motion.div>)}</div></section>

<section className="credits zone"><div className="section-head"><p className="eyebrow dark">CREDITS ROLL</p><h2>THE PEOPLE BEHIND<br/>THE MACHINES</h2></div><div className="people-grid">{Array.from({length:18}).map((_,i)=><motion.div initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%6)*.035}} className="person" key={i}><div>◉<br/>▰</div><small>{['FACULTY','CORE TEAM','TECH TEAM','MEDIA'][i%4]}</small><b>Team Member</b></motion.div>)}</div><p>Made with caffeine, curiosity, and an unreasonable number of zip ties.</p></section>

<section id="register" className="final zone"><PixelCloud className="final-cloud one"/><PixelCloud className="final-cloud two"/><div className="flyer"><div className="pixel-drone"><i/><i/><b/></div><strong>READY TO BUILD?</strong></div><div className="final-content"><p className="eyebrow dark">FINAL LEVEL</p><h2>YOUR NEXT BUILD<br/>STARTS HERE.</h2><p>Bring your team, your tools, and your wildest idea to RoboFiesta’26.</p><PixelButton>Register Now</PixelButton><PixelButton href="#contact" secondary>Contact Organizers</PixelButton></div><div className="ground"><i className="buried-gear">⚙</i><i className="buried-board">▦</i></div></section>

<footer id="contact"><div className="footer-console"><i className="footer-bolt tl"/><i className="footer-bolt tr"/><div className="footer-brand"><span className="mini-bot">● ●</span> ROBOFIESTA’26</div><p>© 2026 RoboFiesta. Built by the RVITM Robotics Community.</p><div className="footer-controls"><a className="footer-game-button" aria-label="Instagram"><Instagram/><span>IG</span></a><a className="footer-game-button" aria-label="LinkedIn"><Linkedin/><span>IN</span></a><a className="footer-game-button" aria-label="YouTube"><Youtube/><span>YT</span></a><a className="footer-game-button" aria-label="Email"><Mail/><span>MAIL</span></a></div><b className="maker-badge"><i/>MADE FOR MAKERS</b></div></footer><FooterPixelSparks/>
<AnimatePresence>{modal&&<motion.div className="modal-back" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setModal(null)}><motion.div className="modal" initial={{y:30}} animate={{y:0}} onClick={e=>e.stopPropagation()}><button aria-label="Close event details" onClick={()=>setModal(null)}><X/></button><span>LEVEL {modal[0]}</span><h2>{modal[1]}</h2><p>{modal[2]} A detailed rulebook, judging criteria, and registration window will land here soon.</p><PixelButton>Get Rulebook</PixelButton></motion.div></motion.div>}</AnimatePresence></main>}
