export type EventDifficulty = 'Open' | 'Beginner' | 'Intermediate' | 'Advanced'

export type EventRecord = {
  slug: string
  level: string
  title: string
  description: string
  teamSize: string
  difficulty: EventDifficulty
  icon: string
  frameColor: string
  artwork: string
  artworkWidth: number
  artworkHeight: number
  prizePool: string
  timing: string
  duration: string
  format: string
  rules: readonly string[]
}

export const fest = {
  name: 'ROBOFIESTA’26',
  date: '16–18 October 2026',
  venue: 'RVITM, Bangalore',
  registrationDeadline: '2026-10-05T23:59:59+05:30',
} as const

const pendingEventRules = [
  'Full event details will be announced soon.',
  'Contact the organisers for the latest guidance.',
] as const

// This catalogue is intentionally plain data so it can be replaced with a CMS response later.
export const events = [
  {
    slug: 'bgmi',
    level: '01',
    title: 'BGMI',
    description: 'Squad up for competitive BGMI matches where survival, eliminations and teamwork all count. Earn points through match placements and kills as you battle through the group stage towards the finals. Join online or on campus and put your four-player squad’s coordination and clutch skills to the test.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◎',
    frameColor: '#e05d31',
    artwork: '/events/bgmi.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'bug-squash',
    level: '02',
    title: 'Bug Squash',
    description: 'Find the faults, fix the code and beat the clock in this debugging competition. Work through three increasingly challenging rounds covering syntax errors, logical mistakes and complex bugs. Accuracy, sharp reasoning and quick repairs will help you stay ahead as the competition gets tougher.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⌘',
    frameColor: '#e48bff',
    artwork: '/events/bug-squash.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'chess',
    level: '03',
    title: 'Chess',
    description: 'Face fellow chess players in a rapid tournament played on Lichess using campus lab computers. With 10 minutes per player, every move tests your planning and composure. Compete across rounds paired by score, build your points tally and challenge for the top spot.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '♛',
    frameColor: '#8d4be7',
    artwork: '/events/chess.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'clash-royale',
    level: '04',
    title: 'Clash Royale',
    description: 'Build your deck and battle through knockout rounds where card combinations, timing and quick decisions can turn a match around. Compete in friendly battles that keep card levels equal, using clever attacks and well-timed defences to outplay rivals and stay in the tournament.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '♜',
    frameColor: '#efb239',
    artwork: '/events/clash-royale.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'code-battle',
    level: '05',
    title: 'Code Battle',
    description: 'Test your programming skills in a timed coding contest where choosing the right challenge matters as much as solving it. Tackle problems across increasing difficulty levels, plan your progression and maximise your score through accurate solutions, logical thinking and smart time management.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚔',
    frameColor: '#f2bc38',
    artwork: '/events/code-battle.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'ctf',
    level: '06',
    title: 'CTF',
    description: 'Put your ethical hacking skills to the test in a story-based cybersecurity challenge. Investigate digital clues, gain access to challenge systems and uncover hidden flags across increasingly difficult levels. Careful analysis, smart use of tools and quick problem-solving help you earn points before time runs out.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚑',
    frameColor: '#58d878',
    artwork: '/events/ctf.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'fifa',
    level: '07',
    title: 'FIFA',
    description: 'Take to the virtual pitch in an on-campus, one-on-one football tournament played on consoles. Choose an official team, control the action and use sharp passing, tactical play and clinical finishing to outscore your opponents. Compete through the league stage and fight for a place in the knockout rounds.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◉',
    frameColor: '#df75ca',
    artwork: '/events/fifa.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'free-fire',
    level: '08',
    title: 'Free Fire',
    description: 'Bring your four-player squad into Free Fire battles where quick decisions and coordinated play can secure the win. Score points through eliminations and match placements as you compete through the group stage and finals. Take part online or on campus and push your team towards the top of the standings.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '✦',
    frameColor: '#ffd845',
    artwork: '/events/free-fire.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'ipl-auction',
    level: '09',
    title: 'IPL Auction',
    description: 'Take the auction seat and build your dream cricket squad through smart bidding and careful budget management. Weigh player strengths, balance your team and compete with rival bidders for your top picks. Cricket knowledge and auction strategy come together in this test of team-building skills.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '₹',
    frameColor: '#84cfff',
    artwork: '/events/ipl-auction.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'minecraft',
    level: '10',
    title: 'Minecraft',
    description: 'Enter the arena for one-on-one Minecraft Java Edition combat, using swords, bows and potions to outplay your opponent. Win best-of-three duels to advance through the knockout bracket, where quick reactions and smart positioning decide who survives. Join on campus or compete remotely.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '▣',
    frameColor: '#8a48cc',
    artwork: '/events/minecraft.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'moneyball',
    level: '11',
    title: 'Moneyball',
    description: 'Step into the role of a football manager: clear the quiz, bid for players, build your squad and choose its formation. Watch your decisions play out in computer-simulated EA SPORTS FC matches, with a transfer market adding negotiation and squad-building twists before the knockouts.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◆',
    frameColor: '#e75244',
    artwork: '/events/moneyball.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'robo-race',
    level: '12',
    title: 'Robo Race',
    description: 'Bring your own robotic car and race against the clock on a track packed with sharp turns, curves and obstacles. Put your robot’s design, speed and control to the test as you navigate the course and aim for the fastest finish.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '↗',
    frameColor: '#ed5b38',
    artwork: '/events/robo-race.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'robo-sumo',
    level: '13',
    title: 'Robo Sumo',
    description: 'Bring your RC-controlled robot into the ring for a one-on-one showdown. Manoeuvre, defend and push your opponent out of the arena to advance through the knockout rounds. Strong engineering, precise control and smart tactics are the keys to becoming the last bot standing.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚙',
    frameColor: '#3fb8db',
    artwork: '/events/robo-sumo.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'save-the-egg',
    level: '14',
    title: 'Save the Egg',
    description: 'Can your design protect an egg from a fall? Create a protective structure and put it through a drop test, combining basic engineering with creative problem-solving. Think carefully about cushioning, stability and impact as you work towards one goal: keeping the egg intact.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◌',
    frameColor: '#70aeef',
    artwork: '/events/save-the-egg.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'tech-auction',
    level: '15',
    title: 'Tech Auction',
    description: 'Clear a technical quiz, bid for technologies in a live auction and use your purchases to build a working prototype in three hours. Mystery envelopes add unexpected advantages or challenges along the way. Finish by demonstrating how your project turns smart bidding and technical skills into a practical solution.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◈',
    frameColor: '#45e4df',
    artwork: '/events/tech-auction.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'treasure-hunt',
    level: '16',
    title: 'Treasure Hunt',
    description: 'Follow the clues, crack the riddles and piece together a trail that leads to the hidden treasure. Combine observation, quick thinking and teamwork as you tackle each puzzle and race to uncover the next clue. Every discovery brings you one step closer to the finish.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '✧',
    frameColor: '#c78b32',
    artwork: '/events/treasure-hunt.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'waste-drift',
    level: '17',
    title: 'Waste Drift',
    description: 'Turn the waste materials provided into a balloon-powered car, using a randomly assigned material as its base. Build within the allotted hour, then compete in one-on-one knockout races where the car travelling farther advances. With no motors or batteries, clever construction makes all the difference.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '➰',
    frameColor: '#f4c63f',
    artwork: '/events/waste-drift.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
] as const satisfies readonly EventRecord[]

export const schedule = {
  'Day 1 — Ignite': [
    ['09:00 AM', 'Opening Ceremony'],
    ['10:30 AM', 'Event Briefing'],
    ['01:00 PM', 'Participant Check-in'],
    ['03:00 PM', 'Challenge Prelims'],
    ['06:00 PM', 'Community Meet'],
  ],
  'Day 2 — Compete': [
    ['09:00 AM', 'Event Rounds'],
    ['11:00 AM', 'Gaming Arena'],
    ['02:00 PM', 'Tech Arena'],
    ['05:00 PM', 'Robo Arena'],
  ],
  'Day 3 — Celebrate': [
    ['10:00 AM', 'Final Rounds'],
    ['01:00 PM', 'Event Showcase'],
    ['03:30 PM', 'Grand Finale'],
    ['05:00 PM', 'Prize Distribution & Closing Ceremony'],
  ],
} as const

export const faqs = [
  {
    question: 'Who can participate in RoboFiesta’26?',
    answer: 'Participation details will be shared with the official event updates.',
  },
  {
    question: 'Can students from other colleges participate?',
    answer: 'Absolutely. RoboFiesta is an open inter-college arena.',
  },
  {
    question: 'What is the maximum team size?',
    answer: 'Team formats will be listed with the official event details.',
  },
  {
    question: 'Is there a registration fee?',
    answer: 'Final registration details and fees will be published in the rulebook.',
  },
  {
    question: 'Are accommodation facilities available?',
    answer: 'Limited accommodation information will be shared with registered outstation teams.',
  },
  {
    question: 'Where can I find the rulebooks?',
    answer: 'Use the rulebook link in the transmission panel or the event challenge cards.',
  },
] as const

export const sponsors = [
  {
    tier: 'Title Sponsor',
    partners: [{ name: 'Title sponsor slot', logoSrc: null, alt: 'Title sponsor logo slot open' }],
  },
  {
    tier: 'Gold Partners',
    partners: [
      { name: 'Gold partner slot 01', logoSrc: null, alt: 'Gold partner logo slot open' },
      { name: 'Gold partner slot 02', logoSrc: null, alt: 'Gold partner logo slot open' },
      { name: 'Gold partner slot 03', logoSrc: null, alt: 'Gold partner logo slot open' },
    ],
  },
  {
    tier: 'Community Partners',
    partners: [
      { name: 'Community slot 01', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 02', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 03', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 04', logoSrc: null, alt: 'Community partner logo slot open' },
    ],
  },
  {
    tier: 'Media Partners',
    partners: [
      { name: 'Media slot 01', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 02', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 03', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 04', logoSrc: null, alt: 'Media partner logo slot open' },
    ],
  },
] as const

export const prizeCategories = [
  { id: 'champion', label: 'Champion', summary: 'Cash prize + trophy', detail: 'Amount to be announced' },
  { id: 'runner-up', label: 'Runner-Up', summary: 'Cash prize + trophy', detail: 'Amount to be announced' },
  { id: 'special-awards', label: 'Special Awards', summary: 'Best Design, Best Innovation, Crowd Favorite', detail: 'Categories to be confirmed' },
] as const

// Names and photos are intentionally not invented before the organising team releases them.
// Replace these records with real profiles when the roster is approved.
export const teamPlaceholders = [
  { id: 'faculty-01', role: 'FACULTY', avatar: 'visor', tone: 'cyan' },
  { id: 'faculty-02', role: 'FACULTY', avatar: 'antenna', tone: 'yellow' },
  { id: 'faculty-03', role: 'FACULTY', avatar: 'cube', tone: 'pink' },
  { id: 'core-01', role: 'CORE TEAM', avatar: 'visor', tone: 'pink' },
  { id: 'core-02', role: 'CORE TEAM', avatar: 'antenna', tone: 'cyan' },
  { id: 'core-03', role: 'CORE TEAM', avatar: 'cube', tone: 'yellow' },
  { id: 'tech-01', role: 'TECH TEAM', avatar: 'cube', tone: 'cyan' },
  { id: 'tech-02', role: 'TECH TEAM', avatar: 'visor', tone: 'yellow' },
  { id: 'tech-03', role: 'TECH TEAM', avatar: 'antenna', tone: 'pink' },
  { id: 'media-01', role: 'MEDIA', avatar: 'antenna', tone: 'pink' },
  { id: 'media-02', role: 'MEDIA', avatar: 'cube', tone: 'cyan' },
  { id: 'media-03', role: 'MEDIA', avatar: 'visor', tone: 'yellow' },
] as const
