export type EventDifficulty = 'Open' | 'Beginner' | 'Intermediate' | 'Advanced'

export type EventRecord = {
  slug: string
  level: string
  title: string
  description: string
  teamSize: string
  difficulty: EventDifficulty
  icon: string
  frameColor: string
  artwork: string
  artworkWidth: number
  artworkHeight: number
  prizePool: string
  timing: string
  duration: string
  format: string
  rules: readonly string[]
}

export const fest = {
  name: 'ROBOFIESTA’26',
  date: '16–18 October 2026',
  venue: 'RVITM, Bangalore',
  registrationDeadline: '2026-10-05T23:59:59+05:30',
} as const

const pendingEventRules = [
  'Full event details will be announced soon.',
  'Contact the organisers for the latest guidance.',
] as const

// This catalogue is intentionally plain data so it can be replaced with a CMS response later.
export const events = [
  {
    slug: 'bgmi',
    level: '01',
    title: 'BGMI',
    description: 'A tactical battleground challenge for sharp squads.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◎',
    frameColor: '#e05d31',
    artwork: '/events/bgmi.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'bug-squash',
    level: '02',
    title: 'Bug Squash',
    description: 'Find the fault, fix it fast, and ship clean code.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⌘',
    frameColor: '#e48bff',
    artwork: '/events/bug-squash.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'chess',
    level: '03',
    title: 'Chess',
    description: 'A focused board battle where every move matters.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '♛',
    frameColor: '#8d4be7',
    artwork: '/events/chess.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'clash-royale',
    level: '04',
    title: 'Clash Royale',
    description: 'Build a smart deck and take control of the arena.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '♜',
    frameColor: '#efb239',
    artwork: '/events/clash-royale.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'code-battle',
    level: '05',
    title: 'Code Battle',
    description: 'Solve, code, and climb through a fast challenge.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚔',
    frameColor: '#f2bc38',
    artwork: '/events/code-battle.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'ctf',
    level: '06',
    title: 'CTF',
    description: 'Find the flag, solve the clue, and secure the win.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚑',
    frameColor: '#58d878',
    artwork: '/events/ctf.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'fifa',
    level: '07',
    title: 'FIFA',
    description: 'Pick a side, play smart, and chase the final whistle.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◉',
    frameColor: '#df75ca',
    artwork: '/events/fifa.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'free-fire',
    level: '08',
    title: 'Free Fire',
    description: 'Drop in, stay alert, and play for the final circle.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '✦',
    frameColor: '#ffd845',
    artwork: '/events/free-fire.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'ipl-auction',
    level: '09',
    title: 'IPL Auction',
    description: 'Build a winning squad through smart auction calls.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '₹',
    frameColor: '#84cfff',
    artwork: '/events/ipl-auction.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'minecraft',
    level: '10',
    title: 'Minecraft',
    description: 'Create, explore, and bring your best build forward.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '▣',
    frameColor: '#8a48cc',
    artwork: '/events/minecraft.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'moneyball',
    level: '11',
    title: 'Moneyball',
    description: 'Make smart calls and keep the scoreboard moving.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◆',
    frameColor: '#e75244',
    artwork: '/events/moneyball.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'robo-race',
    level: '12',
    title: 'Robo Race',
    description: 'Build for speed and take your bot to the finish.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '↗',
    frameColor: '#ed5b38',
    artwork: '/events/robo-race.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'robo-sumo',
    level: '13',
    title: 'Robo Sumo',
    description: 'Hold the ring and outlast the other machine.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '⚙',
    frameColor: '#3fb8db',
    artwork: '/events/robo-sumo.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'save-the-egg',
    level: '14',
    title: 'Save the Egg',
    description: 'Design a safe landing for the fragile payload.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◌',
    frameColor: '#70aeef',
    artwork: '/events/save-the-egg.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'tech-auction',
    level: '15',
    title: 'Tech Auction',
    description: 'Bid wisely and build the strongest tech lineup.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '◈',
    frameColor: '#45e4df',
    artwork: '/events/tech-auction.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'treasure-hunt',
    level: '16',
    title: 'Treasure Hunt',
    description: 'Follow the clues and unlock the next stop.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '✧',
    frameColor: '#c78b32',
    artwork: '/events/treasure-hunt.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
  {
    slug: 'waste-drift',
    level: '17',
    title: 'Waste Drift',
    description: 'Build a scrappy racer and chase the fastest clean run.',
    teamSize: 'Details coming soon',
    difficulty: 'Open',
    icon: '➰',
    frameColor: '#f4c63f',
    artwork: '/events/waste-drift.webp',
    artworkWidth: 794,
    artworkHeight: 1123,
    prizePool: 'Details coming soon',
    timing: 'Schedule coming soon',
    duration: 'To be announced',
    format: 'Details coming soon',
    rules: pendingEventRules,
  },
] as const satisfies readonly EventRecord[]

export const schedule = {
  'Day 1 — Ignite': [
    ['09:00 AM', 'Opening Ceremony'],
    ['10:30 AM', 'Event Briefing'],
    ['01:00 PM', 'Participant Check-in'],
    ['03:00 PM', 'Challenge Prelims'],
    ['06:00 PM', 'Community Meet'],
  ],
  'Day 2 — Compete': [
    ['09:00 AM', 'Event Rounds'],
    ['11:00 AM', 'Gaming Arena'],
    ['02:00 PM', 'Tech Arena'],
    ['05:00 PM', 'Robo Arena'],
  ],
  'Day 3 — Celebrate': [
    ['10:00 AM', 'Final Rounds'],
    ['01:00 PM', 'Event Showcase'],
    ['03:30 PM', 'Grand Finale'],
    ['05:00 PM', 'Prize Distribution & Closing Ceremony'],
  ],
} as const

export const faqs = [
  {
    question: 'Who can participate in RoboFiesta’26?',
    answer: 'Participation details will be shared with the official event updates.',
  },
  {
    question: 'Can students from other colleges participate?',
    answer: 'Absolutely. RoboFiesta is an open inter-college arena.',
  },
  {
    question: 'What is the maximum team size?',
    answer: 'Team formats will be listed with the official event details.',
  },
  {
    question: 'Is there a registration fee?',
    answer: 'Final registration details and fees will be published in the rulebook.',
  },
  {
    question: 'Are accommodation facilities available?',
    answer: 'Limited accommodation information will be shared with registered outstation teams.',
  },
  {
    question: 'Where can I find the rulebooks?',
    answer: 'Use the rulebook link in the transmission panel or the event challenge cards.',
  },
] as const

export const sponsors = [
  {
    tier: 'Title Sponsor',
    partners: [{ name: 'Title sponsor slot', logoSrc: null, alt: 'Title sponsor logo slot open' }],
  },
  {
    tier: 'Gold Partners',
    partners: [
      { name: 'Gold partner slot 01', logoSrc: null, alt: 'Gold partner logo slot open' },
      { name: 'Gold partner slot 02', logoSrc: null, alt: 'Gold partner logo slot open' },
      { name: 'Gold partner slot 03', logoSrc: null, alt: 'Gold partner logo slot open' },
    ],
  },
  {
    tier: 'Community Partners',
    partners: [
      { name: 'Community slot 01', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 02', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 03', logoSrc: null, alt: 'Community partner logo slot open' },
      { name: 'Community slot 04', logoSrc: null, alt: 'Community partner logo slot open' },
    ],
  },
  {
    tier: 'Media Partners',
    partners: [
      { name: 'Media slot 01', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 02', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 03', logoSrc: null, alt: 'Media partner logo slot open' },
      { name: 'Media slot 04', logoSrc: null, alt: 'Media partner logo slot open' },
    ],
  },
] as const

export const prizeCategories = [
  { id: 'champion', label: 'Champion', summary: 'Cash prize + trophy', detail: 'Amount to be announced' },
  { id: 'runner-up', label: 'Runner-Up', summary: 'Cash prize + trophy', detail: 'Amount to be announced' },
  { id: 'special-awards', label: 'Special Awards', summary: 'Best Design, Best Innovation, Crowd Favorite', detail: 'Categories to be confirmed' },
] as const

// Names and photos are intentionally not invented before the organising team releases them.
// Replace these records with real profiles when the roster is approved.
export const teamPlaceholders = [
  { id: 'faculty-01', role: 'FACULTY', avatar: 'visor', tone: 'cyan' },
  { id: 'faculty-02', role: 'FACULTY', avatar: 'antenna', tone: 'yellow' },
  { id: 'faculty-03', role: 'FACULTY', avatar: 'cube', tone: 'pink' },
  { id: 'core-01', role: 'CORE TEAM', avatar: 'visor', tone: 'pink' },
  { id: 'core-02', role: 'CORE TEAM', avatar: 'antenna', tone: 'cyan' },
  { id: 'core-03', role: 'CORE TEAM', avatar: 'cube', tone: 'yellow' },
  { id: 'tech-01', role: 'TECH TEAM', avatar: 'cube', tone: 'cyan' },
  { id: 'tech-02', role: 'TECH TEAM', avatar: 'visor', tone: 'yellow' },
  { id: 'tech-03', role: 'TECH TEAM', avatar: 'antenna', tone: 'pink' },
  { id: 'media-01', role: 'MEDIA', avatar: 'antenna', tone: 'pink' },
  { id: 'media-02', role: 'MEDIA', avatar: 'cube', tone: 'cyan' },
  { id: 'media-03', role: 'MEDIA', avatar: 'visor', tone: 'yellow' },
] as const
